# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VeTOSiOSSDK-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VeTOSiOSSDK-Example

  target 'VeTOSiOSSDK-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VeTOSiOSSDK-ExampleUITests' do
    # Pods for testing
  end

  plugin 'cocoapods-monitor'

  target 'Example' do
 	 pod 'VeTOSiOSSDK-Example', :path => '../', :testspecs => ['Tests']
  end

end
